/*

*	Marketcloud Javascript SDK
*   http://www.marketcloud.it
*
*	Copyright (c) 2015 Herapi SRLS
*
*	Written by Mattia Alfieri <m.alfieri@marketcloud.it>
*

*/
(function(){function h(){window.DEBUG&&console.log(Array.prototype.slice.call(arguments))}function l(c,a,b){var d="",e;for(e in c)b&&a[b]&&0!==a[b].indexOf(c[e])&&(d+=b),d=a[e]?d+e:d+("["+e+"]"),c[e]instanceof Array?d+=l(c[e],a,e):c[e]instanceof Object?d+=l(c[e],a):(d+="="+c[e],d+="&");return d}function p(){try{return new XMLHttpRequest}catch(c){}try{return new ActiveXObject("Msxml3.XMLHTTP")}catch(c){}try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(c){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return null}
Request=function(c){var a=new p;a.open(c.method,c.url,!0);a.onreadystatechange=function(){if(4===a.readyState)if(3<Number(a.status.toString()[0])){if(c.hasOwnProperty("error")){if("function"!==typeof c.error)throw Error("error must be function");h(JSON.parse(a.responseText));c.error(JSON.parse(a.responseText),a.status)}}else if(c.hasOwnProperty("success")){if("function"!==typeof c.success)throw Error("success must be function");h(JSON.parse(a.responseText));c.success(JSON.parse(a.responseText),a.status)}};
a.setRequestHeader("Content-Type","application/json");if(c.hasOwnProperty("headers"))for(var b in c.headers)a.setRequestHeader(b,c.headers[b]);h("Firing this request object ",c);c.hasOwnProperty("data")?a.send(JSON.stringify(c.data)):a.send()};var e=function(c,a,b,f){b={success:b,error:f,headers:{}};b.headers.Authorization=null===d.token?d["public"]:d["public"]+":"+d.token;0>c.indexOf("http://")&&(b.url=d.baseUrl+c);0<Object.keys(a).length&&(c=b.url,a=l(a,a),a=encodeURI(a.substring(0,a.length-1).split(" ").join("+")),
b.url=c+("?"+a));b.method="GET";return Request(b)},k=function(c,a,b){a={success:a,error:b,headers:{}};a.headers.Authorization=null===d.token?d["public"]:d["public"]+":"+d.token;0>c.indexOf("http://")&&(a.url=d.baseUrl+c);a.method="DELETE";return Request(a)},g=function(c,a,b,f){a={success:b,error:f,data:a,headers:{}};a.headers.Authorization=null===d.token?d["public"]:d["public"]+":"+d.token;0>c.indexOf("http://")&&(a.url=d.baseUrl+c);a.method="POST";return Request(a)},m=function(c,a,b,f){a={success:b,
error:f,data:a,headers:{}};a.headers.Authorization=null===d.token?d["public"]:d["public"]+":"+d.token;0>c.indexOf("http://")&&(a.url=d.baseUrl+c);a.method="PATCH";return Request(a)},n=function(c,a,b,f){a={success:b,error:f,data:a,headers:{}};a.headers.Authorization=null===d.token?d["public"]:d["public"]+":"+d.token;0>c.indexOf("http://")&&(a.url=d.baseUrl+c);a.method="PUT";return Request(a)},q="object"==typeof self&&self.self===self&&self||"object"==typeof global&&global.global===global&&global||
this,d={"public":null,token:null,baseUrl:"http://api.marketcloud.it/v0",addresses:{},brands:{},carts:{},categories:{},currencies:{},orders:{},products:{},shippings:{},stores:{},taxes:{},users:{}};d.brands.list=function(c,a){e("/brands",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.brands.getById=function(c,a){e("/brands/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.addresses.create=function(c,a){g("/addresses/",c,function(b){a(null,b.data)},function(b){a(b.errors[0],
null)})};d.addresses.update=function(c,a,b){n("/addresses/"+c,a,function(a){b(null,a.data)},function(a){b(a.errors[0],null)})};d.addresses["delete"]=function(c,a){k("/addresses/"+c,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.addresses.list=function(c,a){e("/addresses",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.addresses.getById=function(c,a){e("/addresses/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.categories.list=function(c,
a){e("/categories",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.categories.getById=function(c,a){e("/categories/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.currencies.list=function(c,a){e("/currencies",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.currencies.getById=function(c,a){e("/currencies/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.orders.create=function(c,a){g("/orders/",c,function(b){a(null,
b.data)},function(b){a(b.errors[0],null)})};d.orders.list=function(c,a){e("/orders",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.orders.getById=function(c,a){e("/orders/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.products.list=function(c,a){e("/products",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.products.getById=function(c,a){e("/products/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.shippings.list=
function(c,a){e("/shippings",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.shippings.getById=function(c,a){e("/shippings/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.stores.create=function(c,a){g("/stores/",c,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.stores.update=function(c,a,b){n("/stores/"+c,a,function(a){b(null,a.data)},function(a){b(a.errors[0],null)})};d.stores["delete"]=function(c,a){k("/stores/"+c,function(b){a(null,
b.data)},function(b){a(b.errors[0],null)})};d.stores.list=function(c,a){e("/stores",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.stores.getById=function(c,a){e("/stores/"+c,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.taxes.list=function(c,a){e("/taxes",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.taxes.getById=function(c,a){e("/taxes/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.users.create=function(c,
a){g("/users/",c,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.users.update=function(c,a,b){n("/users/"+c,a,function(a){b(null,a.data)},function(a){b(a.errors[0],null)})};d.users["delete"]=function(c,a){k("/users/"+c,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.users.list=function(c,a){e("/users",c||{},function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.users.getById=function(c,a){e("/users/"+c,{},function(b){a(null,b.data)},function(b){a(b.errors[0],
null)})};d.users.getCurrent=function(c){if(d.token)e("/users/current",{},function(a){c(null,a.data)},function(a){c(a.errors[0],null)});else throw h("Called users.getCurrent without a token"),Error("Cannot get current user information without a user access token. Obtain a user access token first.");};d.users.authenticate=function(c,a,b){d.token=null;d.user=null;g("/users/authenticate",{password:a,email:c},function(a){d.token=a.data.token;d.user=a.data.user;b(null,a.data)},function(a){b(a.errors[0],
null)})};d.carts.create=function(c,a){var b=null,b=c instanceof Array?{items:c}:c;g("/carts",b,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};d.carts.add=function(c,a,b){if(a instanceof Array)m("/carts/"+c,[{op:"add",items:a}],function(a){b(null,a.data)},function(a){b(a.errors[0],null)});else throw Error("addToCart(cart_id,data,callback) data must be an array [{product_id :1,quantity : 7}]");};d.carts.remove=function(c,a,b){if(a instanceof Array)m("/carts/"+c,[{op:"remove",items:a}],
function(a){b(null,a.data)},function(a){b(a.errors[0],null)});else throw Error("removeFromCart(cart_id,data,callback) data must be an array [{product_id :1,product_id : 7}]");};d.carts.update=function(c,a,b){if(a instanceof Array)m("/carts/"+c,[{op:"update",items:a}],function(a){b(null,a.data)},function(a){b(a.errors[0],null)});else throw Error("removeFromCart(cart_id,data,callback) data must be an array [{product_id :1,product_id : 7}]");};d.carts.getById=function(c,a){e("/carts/"+c,{},function(b){a(null,
b.data)},function(b){a(b.errors[0],null)})};d.carts.getByUser=function(c){if(null===d.user)throw Error("Cannot get current user's cart ca without a user access token. Obtain a user access token first.");e("/users/cart",{},function(a){c(null,a.data)},function(a){c(a.errors[0],null)})};d.carts["delete"]=function(c,a){k("/carts/"+c,function(b){a(null,b.data)},function(b){a(b.errors[0],null)})};q.marketcloud=d})();
